root = "server/go"
tmp_dir = "tmp"

[build]
cmd = "cd server/go && go build -o tmp/main -buildvcs=false ./cmd/safesurf"
bin = "server/go/tmp/main"
full_bin = "server/go/tmp/main"

include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["tmp", "vendor"]

[log]
time = true
