root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o tmp/safesurf -buildvcs=false ./cmd/safesurf"
bin = "tmp/safesurf"
full_bin = "tmp/safesurf"

include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["tmp", "vendor"]

[log]
time = true
